# Generated by Django 3.1.2 on 2020-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orderitems_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI'), ('DC', 'Debit Card'), ('CC', 'Credit Card')], default=False, max_length=3),
            preserve_default=False,
        ),
    ]
