# Generated by Django 3.1.2 on 2020-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitems_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='promo',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='total',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
