# Generated by Django 3.1.2 on 2020-11-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_promo_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='promo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.promo'),
        ),
    ]
