# Generated by Django 3.1.2 on 2020-11-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201116_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='core.cartitems'),
        ),
    ]
