# Generated by Django 3.1.2 on 2020-11-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_users', '0005_useraddress'),
        ('core', '0012_auto_20201116_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_users.useraddress'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.cartitems'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promo'),
        ),
    ]
