# Generated by Django 3.1.2 on 2020-11-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_users', '0005_useraddress'),
        ('core', '0013_auto_20201116_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_users.useraddress'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promo'),
        ),
    ]
