# Generated by Django 3.1.2 on 2020-11-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201116_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.IntegerField(max_length=5),
        ),
    ]
