# Generated by Django 3.1.2 on 2020-11-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201116_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.CharField(max_length=10),
        ),
    ]
