# Generated by Django 3.1.2 on 2020-11-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Email'),
        ),
    ]
