# Generated by Django 3.1.2 on 2020-11-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_users', '0003_auto_20201110_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='is_admin',
        ),
    ]
